[2025-06-08T14:21:29.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:21:29.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_products_csv manual__2025-06-08T14:16:24+00:00 [queued]>
[2025-06-08T14:21:29.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_products_csv manual__2025-06-08T14:16:24+00:00 [queued]>
[2025-06-08T14:21:29.927+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-08T14:21:29.941+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_products_csv> on 2025-06-08 14:16:24+00:00
[2025-06-08T14:21:29.947+0000] {standard_task_runner.py:63} INFO - Started process 2681 to run task
[2025-06-08T14:21:29.953+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'large_csv_processor_dag', 'process_products_csv', 'manual__2025-06-08T14:16:24+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/csv_processor.py', '--cfg-path', '/tmp/tmpl1vzdocx']
[2025-06-08T14:21:29.957+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask process_products_csv
[2025-06-08T14:21:30.025+0000] {task_command.py:426} INFO - Running <TaskInstance: large_csv_processor_dag.process_products_csv manual__2025-06-08T14:16:24+00:00 [running]> on host afb0ae728713
[2025-06-08T14:21:30.130+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='large_csv_processor_dag' AIRFLOW_CTX_TASK_ID='process_products_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:16:24+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:16:24+00:00'
[2025-06-08T14:21:30.132+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:21:30.147+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:21:30.148+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_processor.py", line 40, in process_csv_in_chunks
    with open(sql_file_path, 'w') as sql_file:
PermissionError: [Errno 13] Permission denied: './dags/sql/products_insert.sql'
[2025-06-08T14:21:30.159+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=large_csv_processor_dag, task_id=process_products_csv, run_id=manual__2025-06-08T14:16:24+00:00, execution_date=20250608T141624, start_date=20250608T142129, end_date=20250608T142130
[2025-06-08T14:21:30.173+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 208 for task process_products_csv ([Errno 13] Permission denied: './dags/sql/products_insert.sql'; 2681)
[2025-06-08T14:21:30.215+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T14:21:30.241+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-06-08T14:21:30.263+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T14:21:30.268+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
