[2025-06-08T14:38:37.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:38:37.901+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_monitoring_and_reporting.execute_data_quality_checks manual__2025-06-08T14:38:37+00:00 [queued]>
[2025-06-08T14:38:37.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_monitoring_and_reporting.execute_data_quality_checks manual__2025-06-08T14:38:37+00:00 [queued]>
[2025-06-08T14:38:37.916+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T14:38:37.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): execute_data_quality_checks> on 2025-06-08 14:38:37+00:00
[2025-06-08T14:38:37.943+0000] {standard_task_runner.py:63} INFO - Started process 705 to run task
[2025-06-08T14:38:37.948+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_monitoring_and_reporting', 'execute_data_quality_checks', 'manual__2025-06-08T14:38:37+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/data_monitoring_and_reporting.py', '--cfg-path', '/tmp/tmpou990oaj']
[2025-06-08T14:38:37.953+0000] {standard_task_runner.py:91} INFO - Job 241: Subtask execute_data_quality_checks
[2025-06-08T14:38:38.037+0000] {task_command.py:426} INFO - Running <TaskInstance: data_monitoring_and_reporting.execute_data_quality_checks manual__2025-06-08T14:38:37+00:00 [running]> on host 87e83fb02300
[2025-06-08T14:38:38.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='analytics@company.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_monitoring_and_reporting' AIRFLOW_CTX_TASK_ID='execute_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:38:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:38:37+00:00'
[2025-06-08T14:38:38.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:38:38.204+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2025-06-08T14:38:38.224+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:243 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-08T14:38:38.240+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2025-06-08T14:38:38.259+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2025-06-08T14:38:38.304+0000] {logging_mixin.py:188} INFO - âœ… All data quality checks passed!
[2025-06-08T14:38:38.305+0000] {python.py:237} INFO - Done. Returned value was: {'employees_quality': {'table_name': 'employees', 'total_records': 0, 'null_emails': 0, 'duplicate_emails': 0, 'invalid_ages': 0, 'invalid_salaries': 0, 'last_record_created': None}, 'products_quality': {'table_name': 'products', 'total_records': 0, 'duplicate_skus': 0, 'negative_margin_products': 0, 'negative_stock': 0, 'invalid_ratings': 0, 'last_record_created': None}, 'sales_quality': {'table_name': 'sales_transactions', 'total_records': 0, 'negative_amounts': 0, 'future_dates': 0, 'missing_emails': 0, 'failed_payments': 0, 'last_record_created': None}}
[2025-06-08T14:38:38.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:38:38.333+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_monitoring_and_reporting, task_id=execute_data_quality_checks, run_id=manual__2025-06-08T14:38:37+00:00, execution_date=20250608T143837, start_date=20250608T143837, end_date=20250608T143838
[2025-06-08T14:38:38.377+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-08T14:38:38.393+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
