[2025-06-08T10:59:35.426+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T10:59:35.460+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag.generate_insert_queries scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-06-08T10:59:35.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag.generate_insert_queries scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-06-08T10:59:35.474+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-08T10:59:35.491+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_insert_queries> on 2024-01-01 00:00:00+00:00
[2025-06-08T10:59:35.495+0000] {standard_task_runner.py:63} INFO - Started process 388 to run task
[2025-06-08T10:59:35.499+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag', 'generate_insert_queries', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/job.py', '--cfg-path', '/tmp/tmpqzookqid']
[2025-06-08T10:59:35.502+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask generate_insert_queries
[2025-06-08T10:59:35.559+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres_dag.generate_insert_queries scheduled__2024-01-01T00:00:00+00:00 [running]> on host 6211e2649837
[2025-06-08T10:59:35.648+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag' AIRFLOW_CTX_TASK_ID='generate_insert_queries' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-06-08T10:59:35.650+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T10:59:35.673+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T10:59:35.674+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/job.py", line 25, in generate_insert_queries
    with open('./dasgs/sql/insert_queries.sql', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dasgs/sql/insert_queries.sql'
[2025-06-08T10:59:35.684+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres_dag, task_id=generate_insert_queries, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250608T105935, end_date=20250608T105935
[2025-06-08T10:59:35.696+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task generate_insert_queries ([Errno 2] No such file or directory: './dasgs/sql/insert_queries.sql'; 388)
[2025-06-08T10:59:35.725+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T10:59:35.744+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-06-08T10:59:35.759+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T10:59:35.764+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
